task 05 exceptions in python
